// SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause

#include "vmlinux.h" // generated by build script
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual BSD/GPL";

const volatile int my_pid = 0;

SEC("tp_btf/sched_wakeup")
int handle_tp(u64 *ctx)
{
    struct task_struct *t = (void *)ctx[0];
    bpf_printk("Sched wakeup, PID %d.\n", t->pid);

    return 0;
}
